#!/bin/bash

cd /srv/tftp

cat <<_EOF_ > debian-installer/build/sources.list.udeb.local
# This file is automatically generated
deb [trusted=yes] copy:$PWD/debian-installer/build/ localudebs/
deb http://ftp.se.debian.org/debian testing main/debian-installer
_EOF_
(echo '#include "network-console"'; cat debian-installer/build/pkg-lists/netboot/amd64.cfg) > debian-installer/build/pkg-lists/netboot/amd64.cfg.new
mv debian-installer/build/pkg-lists/netboot/amd64.cfg.new debian-installer/build/pkg-lists/netboot/amd64.cfg
make -C debian-installer*/build/ reallyclean
make -C debian-installer*/build/ rebuild_netboot

tar -xvzf debian-installer*/build/dest/netboot/netboot.tar.gz

version=$(ls /srv/tftp/debian-installer/build/tmp/netboot/tree/lib/modules/)

apt-get download linux-image-${version}
dpkg-deb -x linux-image-${version}*.deb /srv/tftp/linux

mkdir -p mod
cd mod

mkdir -p lib/modules/${version}/kernel/net/netfilter$                     
mkdir -p lib/modules/${version}/kernel/net/ipv4/netfilter
mkdir -p lib/modules/${version}/kernel/net/ipv6/netfilter
