#!/bin/bash

cd /srv/tftp

git clone https://anonscm.debian.org/git/d-i/debian-installer.git
cat <<_EOF_ > debian-installer/build/sources.list.udeb.local
# This file is automatically generated
deb [trusted=yes] copy:$PWD/debian-installer/build/ localudebs/
deb http://ftp.se.debian.org/debian testing main/debian-installer
_EOF_
(echo '#include "network-console"'; cat debian-installer/build/pkg-lists/netboot/amd64.cfg) > debian-installer/build/pkg-lists/netboot/amd64.cfg.new
mv debian-installer/build/pkg-lists/netboot/amd64.cfg.new debian-installer/build/pkg-lists/netboot/amd64.cfg
make -C debian-installer*/build/ reallyclean
make -C debian-installer*/build/ rebuild_netboot
tar -xvzf debian-installer*/build/dest/netboot/netboot.tar.gz
